# release creation for main branche

name: release-generation

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release-generation:
    name: "Test and Run"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Semantic Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          short_tags: false
          bump_each_commit: false
  output:
    name: "Output"
    runs-on: ubuntu-latest
    needs: release-generation
    steps:
      - run: echo ${{needs.release-generation.outputs.version}}
